# Main Page Setup

title: Mousa Pirzada – Portfolio

# Hero Section
name: Mousa Pirzada
headline: Mechatronics Engineering @ Queen’s | AI + Automation Builder
description: >-
  I'm an engineering student specializing in AI-driven automation and robotics.
  With hands-on experience in projects like NoteBuddy, AIVA, and
  award-winning robotics, I build intelligent systems that bridge hardware and software.

profile_image: ./assets/images/profile-image/mousa.jpg

# Resume Link
resume-url: ./assets/resume/mousa_resume.pdf

# Social Icons
external-links:
  linkedin: mousa-pirzada
  github: 20mup
  stackoverflow: 30876291
  medium:
  x-twitter:
  threads:
  instragram:
  youtube:
  discord:
  bluesky:

# Skills Section
skills:
  - category: AI & Automation
    tools:
    - Python
    - OpenAI GPT
    - Whisper
    - Supabase
    - LangChain
    - Playwright
    - Flask / Streamlit

  - category: Robotics & Embedded Systems
    tools:
    - Raspberry Pi Pico
    - Arduino
    - Servo Motor Control
    - Circuit Design
    - Embedded C
    - PWM / GPIO

  - category: Design & Prototyping
    tools:
    - SolidWorks
    - AutoCAD
    - Laser Cutting
    - 3D Printing
    - Fusion 360
    - Cardboard Prototyping

  - category: Tools & DevOps
    tools:
    - Git / GitHub / GitLab
    - Jekyll
    - VS Code
    - Adobe Creative Suite
    - Canva
    - OBS Studio

  - category: Soft Skills
    tools:
      - Technical Communication
      - Team Collaboration
      - Public Speaking
      - Agile Project Management
      - UX Thinking
      - Problem Solving
      - Cross-Disciplinary Leadership

# Contact Form
formspree-key: https://formspree.io/f/mnnvyrjb

# Theme
colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Markdown + Plugins
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects
